### ISSUE TITLE
Rebase

### ISSUE THREAD

**Issue by Alex313031** [StaZhu/enable-chromium-hevc-hardware-decoding#32]
@StaZhu Hi its alex again. Can you rebase your patches for the latest ffmpeg. They did a commit here that made it where the patches wont work anymore because they are off by like a line. > https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/0564e9eec5a741b52804f06c56446cfee582f5cb

**Comment by StaZhu** [comment]
1. The main branch has not update `DEPS` yet (`https://chromium-review.googlesource.com/c/chromium/src/+/3915268`), so the current patch should be working for now, but clearly it will not work after 1-2 days.
2. I simplely write a javascript script to help me do most of the work of generate the patch, i can also upload this script and to this repo and maybe it will be better to run the script before each build instead of apply the patch, whats your suggestion on that?

**Comment by Alex313031** [comment]
@StaZhu Yes please.

**Comment by StaZhu** [comment]
Try this: `https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/blob/main/add-hevc-ffmpeg-decoder-parser.js`

Usage:  `node /path/to/add-hevc-ffmpeg-decoder-parser.js -r /path/to/src/third_party/ffmpeg`
