### ISSUE TITLE
scc profile 无法解码

### ISSUE THREAD

**Issue by ghost** [StaZhu/enable-chromium-hevc-hardware-decoding#55]

**Comment by StaZhu** [comment]
Chrome 目前只支持解码 HEVC Main, Main10, REXT Profile，不支持 SCC Profile。

**Comment by StaZhu** [comment]
> > Chrome 目前只支持解码 HEVC Main, Main10, REXT Profile，不支持 SCC Profile。
> 
> 有计划支持 SCC 吗

现在应该只有Intel特定显卡才支持SCC，另外两家 + Mac都不支持，支持这个有啥意义么？

**Comment by StaZhu** [comment]
cc @taste1981

**Comment by StaZhu** [comment]
> > cc @taste1981, Does Intel support this on Windows?
> 
> Yes, Gen12+ GPU supports HEVC SCC decoding and encoding via QSV (Windows and Linux)

Chrome use D3D11 instead of QSV do decoding, so its unclear if intel support this feature via D3D interface.

**Comment by taste1981** [comment]
We don't have SCC encoding support via HMFT, so corresponding decoding support in Chrome will not be added.

**Comment by taste1981** [comment]
We only consider SCC decoding when this is enabled end-to-end in Chrome. Since there is no encoding support, we will not enable decoding support through D3D11 as well though Intel has private DXVA interface for it.

Besides, D3D12 encoding for SCC/HEVC is not yet defined by Microsoft; And Windows is not yet ready with supporting D3D12 capture/encode, so the encoding support for SCC/HEVC with D3D12 is still below horizon on Windows.

Decoding wise, latest DXVA (D3D11) spec for HEVC decoding does not include HEVC/SCC.
